server:
  port: 9091
spring:
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
      auto-commit: false
      pool-name: spring-data-demo
    url: 'jdbc:postgresql://localhost:5432/software-design-development'
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      connection:
        provider_disables_autocommit: true
        handling_mode: delayed_acquisition_and_release_after_transaction
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: create-drop
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        generate_statistics: true
    #        use_sql_comments: true
    #    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      #      hibernate:
      #        cache:
      #          use_second_level_cache: true
      #          region:
      #            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      generate_statistics: false
  sql:
    init:
      mode: never